### ISSUE TITLE
Integration tests of transactions

### ISSUE THREAD

**Issue by mpapierski** [althea-mesh/clarity#14]
Use https://github.com/ethereum/tests/ `TransactionTests` to automatically verify our implementation of transaction signing.

Description of the tests: https://ethereum-tests.readthedocs.io/en/latest/test_types/transaction_tests.html#sections

The suite is rather simple, and it doesn't contain actual 'signing' verification, only the sender key is derived from "vrs".Seems like https://github.com/althea-mesh/serde-rlp/issues/1 is required to move forward with this as test cases contains only the "rlp" of the transaction.

To generate test cases at runtime based on JSON it could be done in a similiar way as servo does. They use forked "rustc_test" (not sure if it still needs to be a fork?), that generates test functions manually based on input at runtime. Example: https://github.com/servo/html5ever/blob/master/html5ever/tests/tokenizer.rs. 

# Todo

- [x] Sanitize addresses in similiar way as explained in pyethereum
- [x] Compute "sender" of transaction (call recover EC etc.)

# Failed tests

Those tests are failing, and it is unclear why. Only clue I have is that there is some special hardfork verification required.

- [x] TransactionTests/ttGasLimit/TransactionWithHighGas.json@Homestead,EIP150,EIP158,Byzantium,Constantinople@invalid
- [x] TransactionTests/ttRSValue/RightVRSTestF0000000a.json@ALL@invalid
- [x] TransactionTests/ttRSValue/RightVRSTestF0000000b.json@ALL@invalid
- [x] TransactionTests/ttRSValue/RightVRSTestF0000000c.json@ALL@invalid
- [x] ./TransactionTests/ttRSValue/RightVRSTestF0000000d.json
- [x] ./TransactionTests/ttRSValue/RightVRSTestF0000000e.json
- [x] ./TransactionTests/ttRSValue/RightVRSTestF0000000f.json
- [x] TransactionTests/ttRSValue/RightVRSTestVPrefixedBy0.json@ALL@invalid
- [x] TransactionTests/ttRSValue/RightVRSTestVPrefixedBy0_2.json@ALL@invalid
- [x] TransactionTests/ttRSValue/RightVRSTestVPrefixedBy0_3.json@ALL@invalid
- [x] TransactionTests/ttRSValue/TransactionWithSvalueHigh.json@Homestead,EIP150,EIP158,Byzantium,Constantinople@invalid
- [x] TransactionTests/ttRSValue/TransactionWithSvalueLargerThan_c_secp256k1n_x05.json@Homestead,EIP150,EIP158,Byzantium,Constantinople@invalid
- [x] TransactionTests/ttSignature/WrongVRSTestVOverflow.json@ALL@invalid
- [x] TransactionTests/ttVValue/V_overflow64bitSigned.json@Homestead,EIP150,EIP158,Byzantium,Constantinople@invalid
- [x] ./TransactionTests/ttVValue/V_overflow64bitPlus27.json
- [x] ./TransactionTests/ttVValue/V_overflow64bitPlus28.json
- [x] ./TransactionTests/ttVValue/WrongVRSTestVEqual26.json
- [x] ./TransactionTests/ttVValue/WrongVRSTestVEqual29.json
- [x] ./TransactionTests/ttVValue/WrongVRSTestVEqual31.json
- [x] ./TransactionTests/ttVValue/WrongVRSTestVEqual36.json
- [x] TransactionTests/ttVValue/WrongVRSTestVEqual39.json@ALL@invalid
- [x] TransactionTests/ttVValue/WrongVRSTestVEqual41.json@ALL@invalid

*TBD*

Tracking issue #4
